apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/knative-stack
    targetRevision: main
    path: components/knative-eventing
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-eventing
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false