apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/knative-stack
    targetRevision: main
    path: components/knative-serving
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false